[template]
# Required for include files conditionally
cargo_generate_version = ">=0.10.0"

[placeholders.project-description]
type = "string"
prompt = "Project Description"

[placeholders.year]
type = "string"
prompt = "Current Year"
default = "2024"
regex = "^[0-9]{4}$"

[placeholders.bevy]
type = "boolean"
prompt = "Add bevy with debug optimizations?"
default = "n"
choices = ["y","n"]

[conditional.'crate_type == "lib"']
ignore = ["src/main.rs"]

[conditional.'crate_type == "bin"']
ignore = ["src/lib.rs"]
